# CGAN (conditional GAN)

**Author:** Teebone Ding

**Date:** 2019 Feb

Based on Conditional Generative Adversarial Nets (Mirza 2014) [Paper Link](https://arxiv.org/pdf/1411.1784.pdf)

Some useful refs while I implementing my cGAN:
* keras GAN [Link](https://github.com/eriklindernoren/Keras-GAN/blob/master/cgan/cgan.py)
* cGAN in tensorflow version [Link](https://github.com/znxlwm/tensorflow-MNIST-cGAN-cDCGAN)
* Paper summary in Chinese version on Zhihu [Link](https://zhuanlan.zhihu.com/p/23648795)

Using **MNIST fashion dataset** as playground. For more information about [MNIST fashion](https://github.com/zalandoresearch/fashion-mnist)

My SW/HW setting:
* ASUS nVidia GTX 1060 3GB
* RAM: 16GB
* CPU: Intel Core i5-7400 3.00GHz
* Ubuntu 16.04 LTS

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(tf.__version__)

1.12.0


## Load MNIST fashion data and data explore

In [3]:
# Load MNIST fashion data
mnist_dataset = keras.datasets.fashion_mnist
(x_train, y_train), (_, _) = mnist_dataset.load_data()

In [4]:
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [6]:
from tensorflow.keras.utils import to_categorical
y_train_one_hot = to_categorical(y_train)

In [7]:
print(y_train_one_hot.shape)
print(y_train_one_hot[:10])

(60000, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [8]:
y_train[:10]

array([9, 0, 0, 3, 0, 2, 7, 2, 5, 5], dtype=uint8)

In [11]:
# According to https://blog.csdn.net/qq_34355232/article/details/79087075
# and https://github.com/zalandoresearch/fashion-mnist
y_cat = {
    0: "T-shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle boot"
}

# Preprocess training data

In [12]:
x_train = (x_train.astype(np.float32) - 127.5) / 127.5
#x_train = x_train.astype(np.float32)/255.0

In [13]:
x_train = np.expand_dims(x_train,axis=3) # add color channel

In [14]:
x_train.shape

(60000, 28, 28, 1)

## Build Generator and Discriminator
In (Mirza 2014), the paper did not described its architecture really nice. I've modified several parts in both generator and discriminator. This architecture only contain fully connected (FC) layers. In my next iPython notebook, I will try CNN layers to build GAN (cDCGAN).

In [15]:
from tensorflow.keras.layers import Input, Dense, concatenate, Reshape, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam, SGD

In [16]:
z = Input(shape=(100,))    # Uniform distribution noise input
x = Input(shape=(28,28,1)) # image, by real dataset or generator
y = Input(shape=(10,))     # label, MNIST one hot encoded with 10 labels

In [17]:
def build_generator(z,y):
    layer = concatenate([z,y])
    layer = Dense(128,activation='relu')(layer)
    layer = Dense(512,activation='relu')(layer)
    layer = Dense(28*28*1,activation='tanh')(layer)
    layer = Reshape((28,28,1))(layer)
    
    model = Model([z,y],layer)

    return model

G = build_generator(z,y)
G.summary() # not compiled, combined with discriminator and compile.

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 100)          0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            (None, 10)           0                                            
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 110)          0           input_1[0][0]                    
                                                                 input_3[0][0]                    
__________________________________________________________________________________________________
dense (Dense)                   (None, 128)          14208       concatenate[0][0]                
__________

In [18]:
def build_discriminator(x,y):
    x_flatten = Flatten()(x)
    layer = concatenate([x_flatten,y])
    layer = Dense(240,activation='relu')(layer)
    layer = Dense(1,activation='sigmoid')(layer)
    
    model = Model([x,y],layer)
    return model

D = build_discriminator(x,y)

In [19]:
# While training....
# 1. train discriminator first
# 2. train a combined (G+D) model, with D is not trainable (only train G)
# 3. calculate loss value and save weights

In [20]:
# Compile Discriminator model
#sgd = SGD(lr=0.1, momentum=0.5 ,decay= 1.00004)
adam = Adam(0.0002, 0.5)
D.compile(optimizer=adam, loss='binary_crossentropy', metrics=['accuracy'])
D.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 28, 28, 1)    0                                            
__________________________________________________________________________________________________
flatten (Flatten)               (None, 784)          0           input_2[0][0]                    
__________________________________________________________________________________________________
input_3 (InputLayer)            (None, 10)           0                                            
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 794)          0           flatten[0][0]                    
                                                                 input_3[0][0]                    
__________

In [21]:
# Compile combined G+D model with D is not trainable
img = G([z,y])
D.trainable = False
valid = D([img,y])
C = Model([z,y], valid)
C.summary()
C.compile(optimizer=adam,loss='binary_crossentropy')

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 100)          0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            (None, 10)           0                                            
__________________________________________________________________________________________________
model (Model)                   (None, 28, 28, 1)    482448      input_1[0][0]                    
                                                                 input_3[0][0]                    
__________________________________________________________________________________________________
model_1 (Model)                 (None, 1)            191041      model[1][0]                      
          

# Train conditional GAN

In [22]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
tf.logging.set_verbosity(tf.logging.ERROR)

In [23]:
# dataset: x_train, y_train_one_hot

In [24]:
# Randomly generate images from Generator network
def sample_gen_imgs(epoch):
    gen_labels = np.repeat(np.arange(10),10)
    gen_labels_cat = to_categorical(gen_labels, num_classes=10)
    noises = np.random.normal(0,1,(100,100))
    gen_imgs = G.predict([noises,gen_labels_cat])
    gen_imgs = 0.5 * gen_imgs + 0.5

    r,c = 10,10
    fig, axs = plt.subplots(r, c, figsize=(20, 20))
    cnt = 0
    for i in range(r):
        for j in range(c):
            axs[i,j].imshow(gen_imgs[cnt,:,:,0], cmap='gray')
            axs[i,j].set_title("Cat: %s" % y_cat[gen_labels[cnt]])
            axs[i,j].axis('off')
            cnt += 1
    fig.savefig("images/gen_mnist_fashion_%d.png"%epoch)
    plt.close()

In [25]:
#import pdb
import datetime
def train(epochs = 10 ,batch_size = 128): 
    real_label = np.ones((batch_size,1))
    fake_label = np.zeros((batch_size,1))
    
    for epoch in range(epochs):
        epoch += 1
        for step in range(int(60000/batch_size)):
            # Train Discriminator once
            # sample real data from training dataset
            idx = np.random.randint(0, x_train.shape[0], batch_size)
            imgs, labels = x_train[idx], y_train_one_hot[idx]
            # sample noises from normal dist.
            # Somehow I tried uniform dist but cannot trained very well.
            noises = np.random.normal(0,1,(batch_size,100))
            # generate fake images
            gen_imgs = G.predict([noises,labels])
            # Train Discriminator
            d_real_loss = D.train_on_batch([imgs,labels], real_label) 
            d_fake_loss = D.train_on_batch([gen_imgs,labels],fake_label)
            d_loss = 0.5*np.add(d_real_loss,d_fake_loss)
           
            # Train Combined model (generator)
            gen_labels = to_categorical(np.random.randint(0,10, batch_size),num_classes=10)
            # train generator
            g_loss = C.train_on_batch([noises,gen_labels], real_label)
            print("[%s] D-Loss value: %.5f Acc: %.5f G-Loss value: %.5f in epoch: %d"%(datetime.datetime.now(),d_loss[0],d_loss[1], g_loss, epoch),end='\r')
        
        if epoch % 10 == 0:
            print("[%s] D-Loss value: %.5f Acc: %.5f G-Loss value: %.5f in epoch: %d"%(datetime.datetime.now(),d_loss[0],d_loss[1], g_loss, epoch))
            sample_gen_imgs(epoch)
            G.save("models/G_mnist_fashion_%d.h5"%epoch)
            C.save("models/C_mnist_fashion_%d.h5"%epoch)
            D.save("models/D_mnist_fashion_%d.h5"%epoch)

In [26]:
train(epochs=200, batch_size = 100)

[2019-02-14 12:51:51.402211] D-Loss value: 0.59867 Acc: 0.67000 G-Loss value: 1.16305 in epoch: 10
[2019-02-14 12:52:40.182708] D-Loss value: 0.73251 Acc: 0.46500 G-Loss value: 0.92375 in epoch: 20
[2019-02-14 12:53:30.238281] D-Loss value: 0.73269 Acc: 0.44000 G-Loss value: 0.80999 in epoch: 30
[2019-02-14 12:54:21.222648] D-Loss value: 0.70672 Acc: 0.41500 G-Loss value: 0.73908 in epoch: 40
[2019-02-14 12:55:09.798607] D-Loss value: 0.71005 Acc: 0.39000 G-Loss value: 0.75095 in epoch: 50
[2019-02-14 12:55:57.362970] D-Loss value: 0.70212 Acc: 0.47000 G-Loss value: 0.72447 in epoch: 60
[2019-02-14 12:56:44.830046] D-Loss value: 0.70431 Acc: 0.37000 G-Loss value: 0.70557 in epoch: 70
[2019-02-14 12:57:34.140066] D-Loss value: 0.69663 Acc: 0.45000 G-Loss value: 0.71511 in epoch: 80
[2019-02-14 12:58:27.841596] D-Loss value: 0.70060 Acc: 0.37500 G-Loss value: 0.70245 in epoch: 90
[2019-02-14 12:59:21.399008] D-Loss value: 0.69189 Acc: 0.50000 G-Loss value: 0.70246 in epoch: 100
[2019-02-